/*
 * altinn-platform-register
 *
 * Altinn Platform Register
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.Register.Models
{
    /// <summary>
    /// RegisterPartyInputModel
    /// </summary>
    [DataContract(Name = "PartyInput")]
    public partial class RegisterPartyInputModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterPartyInputModel" /> class.
        /// </summary>
        /// <param name="ssn">national identifier.</param>
        /// <param name="orgNo">organization number.</param>
        public RegisterPartyInputModel(string ssn = default(string), string orgNo = default(string))
        {
            this.Ssn = ssn;
            this.OrgNo = orgNo;
        }

        /// <summary>
        /// national identifier
        /// </summary>
        /// <value>national identifier</value>
        [DataMember(Name = "ssn", EmitDefaultValue = false)]
        public string Ssn { get; set; }

        /// <summary>
        /// organization number
        /// </summary>
        /// <value>organization number</value>
        [DataMember(Name = "orgNo", EmitDefaultValue = false)]
        public string OrgNo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RegisterPartyInputModel {\n");
            sb.Append("  Ssn: ").Append(Ssn).Append("\n");
            sb.Append("  OrgNo: ").Append(OrgNo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
