import { TestdataApi } from 'playwright/util/TestdataApi';
import { Token } from './Token';
import { env } from 'playwright/util/helper';

export class ApiRequests {
  private tokenClass: Token;

  constructor() {
    this.tokenClass = new Token();
  }

  public async createSystemInSystemregisterWithAccessPackages(
    vendorOrgNo: string,
    name: string,
    accessPackages?: { urn: string }[],
    redirectUrl?: string,
    rights?: { resource: { value: string; id: string }[] }[],
  ): Promise<string> {
    const vendorId = vendorOrgNo;
    const clientId = `Client_${Date.now()}_${Math.random()}`;

    const payload = {
      Id: `${vendorId}_${name}`,
      Vendor: {
        ID: `0192:${vendorId}`,
      },
      Name: {
        en: name,
        nb: name,
        nn: name,
      },
      Description: {
        en: 'This is auto generated by an integration test. Some data is randomized, but some is not - like this description',
        nb: 'Integrasjonstest. Noe er randomisert her, men mye blir likt.',
        nn: 'integrasjonstest på nynorsk. Noe er randomisert her, men mye blir likt.',
      },
      rights: rights ?? [],
      accessPackages: accessPackages ?? [
        { urn: 'urn:altinn:accesspackage:regnskapsforer-med-signeringsrettighet' },
        { urn: 'urn:altinn:accesspackage:regnskapsforer-uten-signeringsrettighet' },
        { urn: 'urn:altinn:accesspackage:regnskapsforer-lonn' },
        { urn: 'urn:altinn:accesspackage:ansvarlig-revisor' },
        { urn: 'urn:altinn:accesspackage:revisormedarbeider' },
        { urn: 'urn:altinn:accesspackage:skattegrunnlag' },
        { urn: 'urn:altinn:accesspackage:forretningsforer-eiendom' },
      ],
      allowedRedirectUrls: [redirectUrl ?? 'https://www.vg.no'],
      isVisible: false,
      ClientId: [clientId],
    };

    const endpoint = '/authentication/api/v1/systemregister/vendor';
    const scopes = 'altinn:authentication/systemregister.write';

    await this.sendPostRequest<typeof payload, string>(payload, endpoint, scopes, vendorOrgNo);
    return `${vendorId}_${name}`;
  }

  public async cleanUpSystemUsers(
    systemUsers: { id: string }[],
    userPid: string,
    partyOrgNo: string,
  ): Promise<void> {
    const { partyId } = await this.tokenClass.getIds(partyOrgNo);
    const token = await this.tokenClass.getPersonalTokenByPid(userPid);
    for (const systemuser of systemUsers) {
      await this.deleteSystemUser(token, partyId, systemuser.id);
    }
  }

  public async deleteAgentSystemUser(
    vendorOrgNo: string,
    systemId: string,
    partyOrgNo: string,
    externalRef: string,
    userPid: string,
  ): Promise<void> {
    const { partyId, partyUuid } = await this.tokenClass.getIds(partyOrgNo);
    const systemUserId = await this.getSystemUserByQuery(
      vendorOrgNo,
      systemId,
      partyOrgNo,
      externalRef,
    );
    const token = await this.tokenClass.getPersonalTokenByPid(userPid);
    const url = `${env('API_BASE_URL')}/authentication/api/v1/systemuser/agent/${partyId}/${systemUserId}?partyuuid=${partyUuid}`;

    const response = await fetch(url, {
      method: 'DELETE',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error('Failed to delete agent system user:', response.status, errorBody);
      throw new Error(`Failed to delete agent system user: ${response.statusText}`);
    }
  }

  public async deleteSystemInSystemRegister(vendorOrgNo: string, systemName: string) {
    const endpoint = `v1/systemregister/vendor/${vendorOrgNo}_${systemName}`;
    const scopes =
      'altinn:authentication/systemuser.request.write altinn:authentication/systemregister.write altinn:authentication/systemuser.request.read';
    const token = await this.tokenClass.getEnterpriseAltinnToken(vendorOrgNo, scopes);
    const url = `${env('API_BASE_URL')}/authentication/api/${endpoint}`;

    try {
      const response = await fetch(url, {
        method: 'DELETE',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorBody = await response.text();
        console.error('Failed to delete system:', response.status, errorBody);
        throw new Error(`Failed to delete system: ${response.statusText}`);
      }
    } catch (error) {
      console.error('Error during system deletion:', error);
      throw new Error('System deletion failed in SystemRegister. Check logs for details.');
    }
  }

  public async deleteSystemUser(
    token: string,
    partyId: string,
    systemUserId: string,
  ): Promise<void> {
    const endpoint = `v1/systemuser/${partyId}/${systemUserId}`;
    const url = `${env('API_BASE_URL')}/authentication/api/${endpoint}`;

    try {
      const response = await fetch(url, {
        method: 'DELETE',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorBody = await response.text();
        console.error('Failed to delete system user:', response.status, errorBody);
        throw new Error(`Failed to delete system user: ${response.statusText}`);
      }
    } catch (error) {
      console.error('Error during system user deletion:', error);
      throw new Error('System user deletion failed. Check logs for details.');
    }
  }

  public async postClientDelegationAgentRequest(
    vendorOrgNo: string,
    systemId: string,
    accessPackageUrn: string,
    partyOrgNo: string,
    externalRef: string = TestdataApi.generateExternalRef(),
  ) {
    const payload = {
      externalRef,
      systemId,
      partyOrgNo,
      accessPackages: [{ urn: `urn:altinn:accesspackage:${accessPackageUrn}` }],
      redirectUrl: '',
    };

    const endpoint = '/authentication/api/v1/systemuser/request/vendor/agent';
    const scopes =
      'altinn:authentication/systemuser.request.read altinn:authentication/systemuser.request.write';

    return this.sendPostRequest<typeof payload, { confirmUrl: string; id: string }>(
      payload,
      endpoint,
      scopes,
      vendorOrgNo,
    );
  }

  public async deleteRegularSystemUser(
    systemUserId: string,
    partyOrgNo: string,
    userPid: string,
  ): Promise<void> {
    const { partyId } = await this.tokenClass.getIds(partyOrgNo);
    const token = await this.tokenClass.getPersonalTokenByPid(userPid);
    await this.deleteSystemUser(token, partyId, systemUserId);
  }

  public async postSystemuserRequest(
    vendorOrgNo: string,
    externalRef: string,
    systemId: string,
    partyOrgNo: string,
    redirectUrl?: string,
    rights?: { resource: { value: string; id: string }[] }[],
    accessPackages?: { urn: string }[],
  ) {
    const payload = {
      systemId: `${systemId}`,
      partyOrgNo,
      externalRef: externalRef,
      rights: rights ?? [],
      accessPackages: accessPackages ?? [{ urn: 'urn:altinn:accesspackage:baerekraft' }],
      redirectUrl: redirectUrl ?? '',
    };

    const endpoint = '/authentication/api/v1/systemuser/request/vendor';
    const scopes =
      'altinn:authentication/systemuser.request.read altinn:authentication/systemuser.request.write';

    const apiResponse = await this.sendPostRequest<
      typeof payload,
      { confirmUrl: string; id: string }
    >(payload, endpoint, scopes, vendorOrgNo);

    return apiResponse;
  }

  public async approveSystemuserRequest(requestId: string, partyOrgNo: string, userPid: string) {
    const { partyId } = await this.tokenClass.getIds(partyOrgNo);
    const endpoint = `v1/systemuser/request/${partyId}/${requestId}/approve`;
    const url = `${env('API_BASE_URL')}/authentication/api/${endpoint}`;
    const userToken = await this.tokenClass.getPersonalTokenByPid(userPid);

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${userToken}`,
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorBody = await response.text();
        console.error('Failed to approve system user request:', response.status, errorBody);
        throw new Error(`Failed to approve system user request: ${response.statusText}`);
      }
    } catch (error) {
      console.error('Error during system user request approval:', error);
      throw new Error('System user request approval failed. Check logs for details.');
    }
  }

  public async postSystemuserChangeRequest(
    vendorOrgNo: string,
    systemUserId: string,
    changes: {
      requiredRights: { resource: { value: string; id: string }[] }[];
      unwantedRights: { resource: { value: string; id: string }[] }[];
      requiredAccessPackages: { urn: string }[];
      unwantedAccessPackages: { urn: string }[];
    },
  ) {
    const id: string = crypto.randomUUID();

    const payload = {
      unwantedRights: changes.unwantedRights,
      requiredRights: changes.requiredRights,
      requiredAccessPackages: changes.requiredAccessPackages,
      unwantedAccessPackages: changes.unwantedAccessPackages,
    };

    const endpoint = `/authentication/api/v1/systemuser/changerequest/vendor?correlation-id=${id}&system-user-id=${systemUserId}`;
    const scopes =
      'altinn:authentication/systemuser.request.read altinn:authentication/systemuser.request.write';

    const apiResponse = await this.sendPostRequest<
      typeof payload,
      { confirmUrl: string; id: string }
    >(payload, endpoint, scopes, vendorOrgNo);
    return apiResponse;
  }

  public async createSystemSystemRegister(vendorOrgNo: string): Promise<string> {
    const vendorId = vendorOrgNo;
    const clientId = `Client_${Date.now()}` + Math.random();
    // Generate name with max 10 chars: E2E + last 5 digits of timestamp + 2 random digits
    const randomDigits = Math.floor(Math.random() * 100)
      .toString()
      .padStart(2, '0');

    const name = `E2E${Date.now().toString().slice(-5)}${randomDigits}`;

    const payload = {
      Id: `${vendorId}_${name}`,
      Vendor: {
        ID: `0192:${vendorId}`,
      },
      Name: {
        en: `${name}`,
        nb: `${name}`,
        nn: `${name}`,
      },
      Description: {
        en: 'Authentication-e2e-Playwright-English-description',
        nb: 'Authentication-e2e-Playwright-bokmaal-beskrivelse',
        nn: 'Authentication-e2e-Playwright-nynorsk-beskriving',
      },
      rights: [
        {
          resource: [
            {
              value: 'authentication-e2e-test',
              id: 'urn:altinn:resource',
            },
          ],
        },
        {
          resource: [
            {
              value: 'vegardtestressurs',
              id: 'urn:altinn:resource',
            },
          ],
        },
      ],
      allowedRedirectUrls: ['https://altinn.no'],
      isVisible: true,
      ClientId: [clientId],
    };

    const endpoint = '/authentication/api/v1/systemregister/vendor';
    const scopes = 'altinn:authentication/systemregister.write';

    // We expect a JSON response, but we'll just return 'any' or the "name" you need.
    await this.sendPostRequest<typeof payload, string>(payload, endpoint, scopes, vendorOrgNo);
    return name;
  }

  public async getStatusForSystemUserRequest<T>(
    vendorOrgNo: string,
    systemRequestId: string,
  ): Promise<T> {
    const endpoint = `/authentication/api/v1/systemuser/request/vendor/${systemRequestId}`;
    return this.sendGetStatusRequest(endpoint, vendorOrgNo);
  }

  public async getStatusForSystemUserChangeRequest<T>(
    vendorOrgNo: string,
    systemRequestId: string,
  ): Promise<T> {
    const endpoint = `/authentication/api/v1/systemuser/changerequest/vendor/${systemRequestId}`;
    return this.sendGetStatusRequest(endpoint, vendorOrgNo);
  }

  public async getSystemUserByQuery(
    vendorOrgNo: string,
    systemId: string,
    orgno: string,
    externalRef: string,
  ): Promise<string> {
    const endpoint = `/authentication/api/v1/systemuser/vendor/byquery?system-id=${systemId}&orgno=${orgno}&external-ref=${externalRef}`;
    const scopes = 'altinn:authentication/systemuser.request.write';
    const token = await this.tokenClass.getEnterpriseAltinnToken(vendorOrgNo, scopes);

    const url = `${env('API_BASE_URL')}${endpoint}`;

    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorBody = await response.text();
        console.error('Failed to get system user by query:', response.status, errorBody);
        throw new Error(`Failed to get system user by query: ${response.statusText}`);
      }

      const data = await response.json();
      return data.id;
    } catch (error) {
      console.error('Error getting system user by query:', error);
      throw new Error('Failed to get system user by query. Check logs for details.');
    }
  }

  private async sendGetStatusRequest(endpoint: string, vendorOrgNo: string) {
    const scopes =
      'altinn:authentication/systemuser.request.read altinn:authentication/systemuser.request.write';
    const token = await this.tokenClass.getEnterpriseAltinnToken(vendorOrgNo, scopes);
    const url = `${env('API_BASE_URL')}/${endpoint}`;

    const response = await fetch(url, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch status for request. Status: ${response.status}`);
    }

    return await response.json();
  }

  private async sendPostRequest<TPayload, TResponse>(
    payload: TPayload,
    endpoint: string,
    scopes: string,
    vendorOrgNo: string,
  ): Promise<TResponse> {
    const baseUrl = env('API_BASE_URL');
    let url = baseUrl + endpoint;

    const token = await this.tokenClass.getEnterpriseAltinnToken(vendorOrgNo, scopes);

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error(`HTTP Error! Status: ${response.status}, Body: ${errorBody}`);
      throw new Error(`HTTP error! Status: ${response.status}, Body: ${errorBody}`);
    }

    return (await response.json()) as TResponse;
  }
}
