using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Altinn.AccessManagement.UI.Core.Models.SystemUser.Frontend
{
    /// <summary>
    /// Response DTO through the API after Vendor calls to Create a new Request for a SystemUser
    /// </summary>
    public class SystemUserClientRequestFE
    {
        /// <summary>
        /// Guid in the format of a UUID-v4 Id generated by us; also will be reused by the SystemUser when it is approved.
        /// We use a Guid rather than the External Request Id, to facilitate Db administration and the possiblity to delete and renew a SystemUser.
        /// </summary>
        [Required]
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Initially the request is "new", 
        /// other values are "accepted", "rejected", "denied"
        /// </summary>
        [Required]
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Optional redirect URL to navigate to after the customer has accepted/denied the Request
        /// </summary>    
        [JsonPropertyName("redirectUrl")]
        public string RedirectUrl { get; set; }

        /// <summary>
        /// System information from the system register
        /// </summary>
        [JsonPropertyName("system")]
        public RegisteredSystemFE System { get; set; }
    }
}