using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Altinn.AccessManagement.UI.Core.Models.AccessPackage.Frontend;
using Altinn.AccessManagement.UI.Core.Models.ResourceRegistry.Frontend;

namespace Altinn.AccessManagement.UI.Core.Models.SystemUser.Frontend
{
    /// <summary>
    /// Response DTO through the API after Vendor calls to Create a new Request for a SystemUser
    /// </summary>
    public class SystemUserRequestFE
    {
        /// <summary>
        /// Guid in the format of a UUID-v4 Id generated by us; also will be reused by the SystemUser when it is approved.
        /// We use a Guid rather than the External Request Id, to facilitate Db administration and the possiblity to delete and renew a SystemUser.
        /// </summary>
        [Required]
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// PartyId of the SystemUser's Party (the customer that delegates rights to the systemuser).
        /// </summary>
        [Required]
        [JsonPropertyName("partyId")]
        public int PartyId { get; set; }

        /// <summary>
        /// PartyUuid of the SystemUser's Party (the customer that delegates rights to the systemuser).
        /// </summary>
        [Required]
        [JsonPropertyName("partyUuid")]
        public Guid PartyUuid { get; set; }

        /// <summary>
        /// Initially the request is "new", 
        /// other values are "accepted", "rejected", "denied"
        /// </summary>
        [Required]
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Optional redirect URL to navigate to after the customer has accepted/denied the Request
        /// </summary>    
        [JsonPropertyName("redirectUrl")]
        public string RedirectUrl { get; set; }

        /// <summary>
        /// System information from the system register
        /// </summary>
        [JsonPropertyName("system")]
        public RegisteredSystemFE System { get; set; }

        /// <summary>
        /// List of resources information
        /// </summary>
        [JsonPropertyName("resources")]
        public List<ServiceResourceFE> Resources { get; set; } = new List<ServiceResourceFE>();

        /// <summary>
        /// List of access package information (with resources)
        /// </summary>
        [JsonPropertyName("accessPackages")]
        public List<AccessPackageFE> AccessPackages { get; set; } = new List<AccessPackageFE>();

        /// <summary>
        /// The date and time the Request was created,
        /// used to determine if the Request is still valid.
        /// </summary>
        [JsonPropertyName("created")]
        public DateTimeOffset Created { get; set; }

        /// <summary>
        /// Tracks if the original user creating the Request have escalated the Approval of this Request
        /// to somebody else in the organisation with AccessManager (Package:Tilgangsstyring)
        /// </summary>
        [JsonPropertyName("escalated")]
        public bool Escalated { get; set; }

        /// <summary>
        /// Indicates if the user is allowed to escalate the approval of this Request
        /// is only true for the current logged in user trying to read the Request
        /// if he has any Relation (Right, AccessPackage or Role) with the PartyUuid
        /// but does not have AccessManager (Package:Tilgangsstyring) yet.
        /// </summary>
        [JsonPropertyName("userMayEscalateButNotApprove")]
        public bool UserMayEscalateButNotApprove { get; set; }
    }
}