template: |
  # Changelog
  $CHANGES
  
  See details of [all code changes](https://github.com/acn-dgopa/altinn-access-management-frontend/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release 
  
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'infrastructure'
      - 'automation'
      - 'documentation'
      - 'dependencies'
  - title: '🏎 Performance'
    label: 'performance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'