template: |
  # Changelog
  $CHANGES
  
  See details of [all code changes](https://github.com/altinn/altinn-access-management-frontend/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release 
  
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'kind/documentation'
      - 'dependencies'
      - 'enhancement'
      - 'kind/chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
