/*
 * altinn-platform-profile
 *
 * Altinn Platform Profile
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.Profile.Models
{
    /// <summary>
    /// ProfileOrganizationModel
    /// </summary>
    [DataContract(Name = "Organization")]
    public partial class ProfileOrganizationModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfileOrganizationModel" /> class.
        /// </summary>
        /// <param name="orgNumber">Identifier.</param>
        /// <param name="name">Name of the organization.</param>
        /// <param name="unitType">Unit Type.</param>
        public ProfileOrganizationModel(string orgNumber = default(string), string name = default(string), string unitType = default(string))
        {
            this.OrgNumber = orgNumber;
            this.Name = name;
            this.UnitType = unitType;
        }

        /// <summary>
        /// Identifier
        /// </summary>
        /// <value>Identifier</value>
        [DataMember(Name = "OrgNumber", EmitDefaultValue = false)]
        public string OrgNumber { get; set; }

        /// <summary>
        /// Name of the organization
        /// </summary>
        /// <value>Name of the organization</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Unit Type
        /// </summary>
        /// <value>Unit Type</value>
        [DataMember(Name = "UnitType", EmitDefaultValue = false)]
        public string UnitType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfileOrganizationModel {\n");
            sb.Append("  OrgNumber: ").Append(OrgNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UnitType: ").Append(UnitType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
