export const inboxPage = {
  archives: 'button[onclick*="href=\'/ui/MessageBox/Archive\'"]',
  deleted: 'button[onclick*="href=\'/ui/MessageBox/Trash\'"]',
  messageBoxElements: '#messageBoxElementList',
  inboxElements: {
    meldingConfirm: '.elementHeader',
    inboxElementsHeading: 'h2.a-fontSizeS',
    brekreftetMeldingButton: '.card.expanded button[onclick^="confirmCorrespondence"]',
    activityLogsButton: 'a[data-url^="/ui/ActivityLog/GetActivityLogForActiveReporteeElement"]',
    activityLogDateRow1: '.a-list > :nth-child(1) > .row > .col-md-4',
    activityLogDescRow1: 'div[class="col-12 col-md-3"]',
    activityLogDesc2Row1: 'div[class="col-12 col-md-5"]',
    forwardMelding: '.card.expanded button[data-url*="Correspondence/Forward"',
    receiver: '#Recipients',
    forwardButton: '.a-btn-success',
    forwardToReceiver:
      '.card.expanded button[data-url*="/ui/Messagebox/ForwardingRecipientsForActiveElement"',
    searchPerson: '#searchForPersonInput',
    searchResults: 'span[class="a-js-noSearchResults"]',
    addNewPersonButton: '.a-btn.a-btn-action.a-fullWidthBtn.a-fontSizeXS',
    submitEmailRights: '#submit-email-rights',
    recipientButton: '.a-btn.a-btn-success',
    submitEmail: '#submit-email-input',
    forwardRecipient: ':nth-child(7) > :nth-child(2) > .a-btn',
  },
  deleteElements: {
    deleteCorrespondence: '.a-btn-link.a-btn-md-block.pb-1.dropdown-menu-button',
    softDelete: 'span[class="a-btn-icon-text"]',
    slettede: 'button[onclick*="ui/MessageBox/Trash"',
    backButton: '.ai-stack-1x.ai.ai-back',
    restoreButton: '.card.expanded button[onclick*="RestoreActiveElement"]',
    backToInbox: 'button[class="a-btn-link float-right float-md-none"]',
    removeMessageRights:
      '#DelegatedInstances-Delete > .a-list-container > .a-list > .a-dotted > .row > .col',
    navigateToInbox: 'span[class="a-hvr-underline"]',
    navigateToProfile: 'span[class="a-hvr-underline a-js-onboardingTarget-2"]',
  },
  SearchInbox: {
    inboxCheckbox: '[id="ElementSearch.IncludeMessageBox"]',
    arkivCheckbox: '[id="ElementSearch.IncludeArchive"]',
    deletedCheckbox: '[id="ElementSearch.IncludeDeleted"]',
  },
};
