/*
 * Altinn.AccessManagement
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.AccessManagement.Models
{
    /// <summary>
    /// AccessManagementRightsDelegationResponseExternalModel
    /// </summary>
    [DataContract(Name = "RightsDelegationResponseExternal")]
    public partial class AccessManagementRightsDelegationResponseExternalModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessManagementRightsDelegationResponseExternalModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccessManagementRightsDelegationResponseExternalModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessManagementRightsDelegationResponseExternalModel" /> class.
        /// </summary>
        /// <param name="to">to (required).</param>
        /// <param name="rightDelegationResults">rightDelegationResults (required).</param>
        public AccessManagementRightsDelegationResponseExternalModel(List<AccessManagementAttributeMatchExternalModel> to = default(List<AccessManagementAttributeMatchExternalModel>), List<AccessManagementRightDelegationResultExternalModel> rightDelegationResults = default(List<AccessManagementRightDelegationResultExternalModel>))
        {
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new ArgumentNullException("to is a required property for AccessManagementRightsDelegationResponseExternalModel and cannot be null");
            }
            this.To = to;
            // to ensure "rightDelegationResults" is required (not null)
            if (rightDelegationResults == null)
            {
                throw new ArgumentNullException("rightDelegationResults is a required property for AccessManagementRightsDelegationResponseExternalModel and cannot be null");
            }
            this.RightDelegationResults = rightDelegationResults;
        }

        /// <summary>
        /// Gets or Sets To
        /// </summary>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public List<AccessManagementAttributeMatchExternalModel> To { get; set; }

        /// <summary>
        /// Gets or Sets RightDelegationResults
        /// </summary>
        [DataMember(Name = "rightDelegationResults", IsRequired = true, EmitDefaultValue = true)]
        public List<AccessManagementRightDelegationResultExternalModel> RightDelegationResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccessManagementRightsDelegationResponseExternalModel {\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  RightDelegationResults: ").Append(RightDelegationResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
