/*
 * Altinn.AccessManagement
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.AccessManagement.Models
{
    /// <summary>
    /// AccessManagementRuleQueryModel
    /// </summary>
    [DataContract(Name = "RuleQuery")]
    public partial class AccessManagementRuleQueryModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessManagementRuleQueryModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccessManagementRuleQueryModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessManagementRuleQueryModel" /> class.
        /// </summary>
        /// <param name="parentPartyId">parentPartyId.</param>
        /// <param name="keyRolePartyIds">keyRolePartyIds (required).</param>
        /// <param name="offeredByPartyId">offeredByPartyId.</param>
        /// <param name="resources">resources.</param>
        /// <param name="coveredBy">coveredBy (required).</param>
        public AccessManagementRuleQueryModel(int parentPartyId = default(int), List<int> keyRolePartyIds = default(List<int>), int offeredByPartyId = default(int), List<List<AccessManagementAttributeMatchModel>> resources = default(List<List<AccessManagementAttributeMatchModel>>), List<AccessManagementAttributeMatchModel> coveredBy = default(List<AccessManagementAttributeMatchModel>))
        {
            // to ensure "keyRolePartyIds" is required (not null)
            if (keyRolePartyIds == null)
            {
                throw new ArgumentNullException("keyRolePartyIds is a required property for AccessManagementRuleQueryModel and cannot be null");
            }
            this.KeyRolePartyIds = keyRolePartyIds;
            // to ensure "coveredBy" is required (not null)
            if (coveredBy == null)
            {
                throw new ArgumentNullException("coveredBy is a required property for AccessManagementRuleQueryModel and cannot be null");
            }
            this.CoveredBy = coveredBy;
            this.ParentPartyId = parentPartyId;
            this.OfferedByPartyId = offeredByPartyId;
            this.Resources = resources;
        }

        /// <summary>
        /// Gets or Sets ParentPartyId
        /// </summary>
        [DataMember(Name = "parentPartyId", EmitDefaultValue = false)]
        public int ParentPartyId { get; set; }

        /// <summary>
        /// Gets or Sets KeyRolePartyIds
        /// </summary>
        [DataMember(Name = "keyRolePartyIds", IsRequired = true, EmitDefaultValue = true)]
        public List<int> KeyRolePartyIds { get; set; }

        /// <summary>
        /// Gets or Sets OfferedByPartyId
        /// </summary>
        [DataMember(Name = "offeredByPartyId", EmitDefaultValue = false)]
        public int OfferedByPartyId { get; set; }

        /// <summary>
        /// Gets or Sets Resources
        /// </summary>
        [DataMember(Name = "resources", EmitDefaultValue = true)]
        public List<List<AccessManagementAttributeMatchModel>> Resources { get; set; }

        /// <summary>
        /// Gets or Sets CoveredBy
        /// </summary>
        [DataMember(Name = "coveredBy", IsRequired = true, EmitDefaultValue = true)]
        public List<AccessManagementAttributeMatchModel> CoveredBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccessManagementRuleQueryModel {\n");
            sb.Append("  ParentPartyId: ").Append(ParentPartyId).Append("\n");
            sb.Append("  KeyRolePartyIds: ").Append(KeyRolePartyIds).Append("\n");
            sb.Append("  OfferedByPartyId: ").Append(OfferedByPartyId).Append("\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  CoveredBy: ").Append(CoveredBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
