/*
 * Altinn.AccessManagement
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.AccessManagement.Models
{
    /// <summary>
    /// AccessManagementOrganizationModel
    /// </summary>
    [DataContract(Name = "Organization")]
    public partial class AccessManagementOrganizationModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessManagementOrganizationModel" /> class.
        /// </summary>
        /// <param name="orgNumber">orgNumber.</param>
        /// <param name="name">name.</param>
        /// <param name="unitType">unitType.</param>
        /// <param name="telephoneNumber">telephoneNumber.</param>
        /// <param name="mobileNumber">mobileNumber.</param>
        /// <param name="faxNumber">faxNumber.</param>
        /// <param name="eMailAddress">eMailAddress.</param>
        /// <param name="internetAddress">internetAddress.</param>
        /// <param name="mailingAddress">mailingAddress.</param>
        /// <param name="mailingPostalCode">mailingPostalCode.</param>
        /// <param name="mailingPostalCity">mailingPostalCity.</param>
        /// <param name="businessAddress">businessAddress.</param>
        /// <param name="businessPostalCode">businessPostalCode.</param>
        /// <param name="businessPostalCity">businessPostalCity.</param>
        /// <param name="unitStatus">unitStatus.</param>
        public AccessManagementOrganizationModel(string orgNumber = default(string), string name = default(string), string unitType = default(string), string telephoneNumber = default(string), string mobileNumber = default(string), string faxNumber = default(string), string eMailAddress = default(string), string internetAddress = default(string), string mailingAddress = default(string), string mailingPostalCode = default(string), string mailingPostalCity = default(string), string businessAddress = default(string), string businessPostalCode = default(string), string businessPostalCity = default(string), string unitStatus = default(string))
        {
            this.OrgNumber = orgNumber;
            this.Name = name;
            this.UnitType = unitType;
            this.TelephoneNumber = telephoneNumber;
            this.MobileNumber = mobileNumber;
            this.FaxNumber = faxNumber;
            this.EMailAddress = eMailAddress;
            this.InternetAddress = internetAddress;
            this.MailingAddress = mailingAddress;
            this.MailingPostalCode = mailingPostalCode;
            this.MailingPostalCity = mailingPostalCity;
            this.BusinessAddress = businessAddress;
            this.BusinessPostalCode = businessPostalCode;
            this.BusinessPostalCity = businessPostalCity;
            this.UnitStatus = unitStatus;
        }

        /// <summary>
        /// Gets or Sets OrgNumber
        /// </summary>
        [DataMember(Name = "orgNumber", EmitDefaultValue = true)]
        public string OrgNumber { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets UnitType
        /// </summary>
        [DataMember(Name = "unitType", EmitDefaultValue = true)]
        public string UnitType { get; set; }

        /// <summary>
        /// Gets or Sets TelephoneNumber
        /// </summary>
        [DataMember(Name = "telephoneNumber", EmitDefaultValue = true)]
        public string TelephoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets MobileNumber
        /// </summary>
        [DataMember(Name = "mobileNumber", EmitDefaultValue = true)]
        public string MobileNumber { get; set; }

        /// <summary>
        /// Gets or Sets FaxNumber
        /// </summary>
        [DataMember(Name = "faxNumber", EmitDefaultValue = true)]
        public string FaxNumber { get; set; }

        /// <summary>
        /// Gets or Sets EMailAddress
        /// </summary>
        [DataMember(Name = "eMailAddress", EmitDefaultValue = true)]
        public string EMailAddress { get; set; }

        /// <summary>
        /// Gets or Sets InternetAddress
        /// </summary>
        [DataMember(Name = "internetAddress", EmitDefaultValue = true)]
        public string InternetAddress { get; set; }

        /// <summary>
        /// Gets or Sets MailingAddress
        /// </summary>
        [DataMember(Name = "mailingAddress", EmitDefaultValue = true)]
        public string MailingAddress { get; set; }

        /// <summary>
        /// Gets or Sets MailingPostalCode
        /// </summary>
        [DataMember(Name = "mailingPostalCode", EmitDefaultValue = true)]
        public string MailingPostalCode { get; set; }

        /// <summary>
        /// Gets or Sets MailingPostalCity
        /// </summary>
        [DataMember(Name = "mailingPostalCity", EmitDefaultValue = true)]
        public string MailingPostalCity { get; set; }

        /// <summary>
        /// Gets or Sets BusinessAddress
        /// </summary>
        [DataMember(Name = "businessAddress", EmitDefaultValue = true)]
        public string BusinessAddress { get; set; }

        /// <summary>
        /// Gets or Sets BusinessPostalCode
        /// </summary>
        [DataMember(Name = "businessPostalCode", EmitDefaultValue = true)]
        public string BusinessPostalCode { get; set; }

        /// <summary>
        /// Gets or Sets BusinessPostalCity
        /// </summary>
        [DataMember(Name = "businessPostalCity", EmitDefaultValue = true)]
        public string BusinessPostalCity { get; set; }

        /// <summary>
        /// Gets or Sets UnitStatus
        /// </summary>
        [DataMember(Name = "unitStatus", EmitDefaultValue = true)]
        public string UnitStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccessManagementOrganizationModel {\n");
            sb.Append("  OrgNumber: ").Append(OrgNumber).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UnitType: ").Append(UnitType).Append("\n");
            sb.Append("  TelephoneNumber: ").Append(TelephoneNumber).Append("\n");
            sb.Append("  MobileNumber: ").Append(MobileNumber).Append("\n");
            sb.Append("  FaxNumber: ").Append(FaxNumber).Append("\n");
            sb.Append("  EMailAddress: ").Append(EMailAddress).Append("\n");
            sb.Append("  InternetAddress: ").Append(InternetAddress).Append("\n");
            sb.Append("  MailingAddress: ").Append(MailingAddress).Append("\n");
            sb.Append("  MailingPostalCode: ").Append(MailingPostalCode).Append("\n");
            sb.Append("  MailingPostalCity: ").Append(MailingPostalCity).Append("\n");
            sb.Append("  BusinessAddress: ").Append(BusinessAddress).Append("\n");
            sb.Append("  BusinessPostalCode: ").Append(BusinessPostalCode).Append("\n");
            sb.Append("  BusinessPostalCity: ").Append(BusinessPostalCity).Append("\n");
            sb.Append("  UnitStatus: ").Append(UnitStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
