/*
 * Altinn.AccessManagement
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;

namespace Altinn.AccessManagement.UI.Integrations.AccessManagement.Models
{
    /// <summary>
    /// Defines AuthorizedPartyTypeExternal
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccessManagementAuthorizedPartyTypeExternalModel
    {
        /// <summary>
        /// Enum None for value: None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 1,

        /// <summary>
        /// Enum Person for value: Person
        /// </summary>
        [EnumMember(Value = "Person")]
        Person = 2,

        /// <summary>
        /// Enum Organization for value: Organization
        /// </summary>
        [EnumMember(Value = "Organization")]
        Organization = 3,

        /// <summary>
        /// Enum SelfIdentified for value: SelfIdentified
        /// </summary>
        [EnumMember(Value = "SelfIdentified")]
        SelfIdentified = 4
    }

}
