export enum amUIPath {
  Users = 'users',
  UserRights = 'users/:id',
  MyClients = 'my-clients',
  Reportees = 'received-from',
  ReporteeRights = 'received-from/:id',
  PoaOverview = 'poa-overview',
  PoaOverviewInstance = 'poa-overview/instance',
  PackagePoaDetails = 'poa-overview/access-package/:id',
  ServicePoaDetails = 'poa-overview/service/:id',
  Settings = 'settings',
  Requests = 'requests',
  DraftRequest = 'requests/resource',
  ClientAdministration = 'clientadministration',
  ClientAdministrationAgent = 'clientadministration/agent/:id',
  ClientAdministrationClient = 'clientadministration/client/:id',
  Altinn2Account = 'altinn2account',
  Maskinporten = 'maskinporten',
  MaskinportenSupplier = 'maskinporten/supplier/:id',
  MaskinportenConsumer = 'maskinporten/consumer/:id',
}
