name: 'Continuous Integration: Frontend'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - backend/**

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - backend/**

jobs:
  ci:
    name: 'Continous Integration'
    uses: './.github/workflows/template-build-and-test-frontend.yml'