name: 'Continuous Integration: Backend'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - backend/**

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - backend/**

jobs:
  ci:
    name: 'Continous Integration'
    secrets: inherit
    uses: './.github/workflows/template-build-and-test-backend.yml'
