name: "Continuous Integration: Frontend"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - src/**

  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - src/**

jobs:
  ci:
    name: "Continous Integration"
    uses: "./.github/workflows/template-build-and-test-frontend.yml"
