name: 'Continuous Integration: Backend'

on:
  push:
    # branches: [ main ]
    # paths:
    #   - backend/**

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - backend/**

jobs:
  ci:
    name: 'Continous Integration'
    uses: './template-build-and-test-backend.yml'
