name: Cypress e2e tests

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - at21
          - at22
          - at23
          - at24
          - tt02
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Substitute package.json Variables
        run: sed -i 's\%EnvironmentToRunTests%\at22\g' cypress/package.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress
          start: yarn run test
          browser: chrome
