name: Cypress e2e tests

on:
  push:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: cypress
          browser: chrome
          build: yarn build
          start: yarn test
          wait-on: "http://localhost:3000"

# EnvironmentToRunTests