name: Cypress End-to-End Tests Schedule

on:
  push:
  schedule:
    - cron:  '0 8 * * *' # every day at 08:00

jobs:
  schedule:
    strategy:
      matrix:
        environment: [at21, at22, at23, at24, tt02]
    uses: './.github/workflows/cypress-template.yml'
