name: Cypress e2e tests

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - at21
          - at22
          - at23
          - at24
          - tt02
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Substitute package.json Variables
        run: sed -i 's\%EnvironmentToRunTests%\at22\g' cypress/package.json
      - name: list file
        run: cypress/package.json
      - name: Cypress run
        uses: cypress-io/github-action@v3
        env:
          EnvironmentToRunTests: at21
        with:
          project: cypress
          browser: chrome
          build: yarn build
          start: yarn test
