name: 'Deploy: AT'

run-name: 'AT environments: ${{ github.sha }}'

on:
  push:
    branches: [main]

jobs:
  build-and-push-container:
    name: 'Build and Push Container'
    uses: './.github/workflows/template-build-and-push-container.yml'
    with:
      tag: ${{ github.sha }}

  deploys-main:
    name: 'Deploys Main'
    needs: build-and-push-container
    strategy:
      fail-fast: false
      matrix:
        environment: [AT21, AT22, AT23, AT24]
    uses: './.github/workflows/template-deploy-container.yml'
    with:
      environment: ${{ matrix.environment }}
      tag: ${{ github.sha }}

  cypress-main:
    name: 'Cypress Tests'
    needs: deploys-main
    strategy:
      fail-fast: false
      matrix:
        environment: [AT21, AT22, AT23, AT24]
    uses: './.github/workflows/template-test-cypress.yml'
    with:
      environment: ${{ matrix.environment }}
 