name: 'Deploy: AT'

run-name: 'AT environments: ${{ github.sha }}'

on:
  push:
    branches: ['*']

jobs:
  containerize:
    name: 'Containerize'
    uses: './.github/workflows/template-build-and-push-container.yml'
    with:
      tag: ${{ github.sha }}

  # deploy-main:
  #   name: 'Environment'
  #   needs: containerize
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       environment: [AT23, AT24]
  #   uses: './.github/workflows/template-deploy-container.yml'
  #   secrets: inherit
  #   with:
  #     environment: ${{ matrix.environment }}
  #     tag: ${{ github.sha }}

  playwright-main:
    name: 'Playwright'
    # needs: deploy-main
    strategy:
      fail-fast: false
      matrix:
        environment: [AT24]

    uses: './.github/workflows/template-playwright.yml'

    with:
      environment: ${{ matrix.environment }}
