name: 'Deploy: Release'

run-name: ${{ github.ref_name }}

on:
  push:

jobs:
  playwright-release-to-tt02:
    name: 'Playwright'
    # needs: deploy-release-to-tt02
    uses: './.github/workflows/playwright.yml'
    with:
      environment: tt02

  # containerize:
  #   name: 'Containerize'
  #   uses: './.github/workflows/template-build-and-push-container.yml'
  #   with:
  #     tag: ${{ github.ref_name }}

  # deploy-release-to-tt02:
  #   name: 'Environment (TT02)'
  #   needs: containerize
  #   uses: './.github/workflows/template-deploy-container.yml'
  #   secrets: inherit
  #   with:
  #     environment: tt02
  #     tag: ${{ github.ref_name }}


  # deploys-release-to-prod:
  #   name: 'Environment (Prod)'
  #   needs: deploy-release-to-tt02
  #   uses: './.github/workflows/template-deploy-container.yml'
  #   secrets: inherit
  #   with:
  #     environment: prod
  #     tag: ${{ github.ref_name }}
