name: Generate ECR Image

on:
  workflow_dispatch
jobs:
  get-images-list:
    runs-on: ubuntu-latest
    
      - name: Get All Images On Github container registry
        run: |
         - uses: octokit/request-action@v2.x
      #- name: apirun
        id: get_package_versions
        with:
          route: GET /user/packages/container/altinn-access-management-frontend/versions
          mediaType: | # The | is significant!
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Generates release.yml with package version
        responses=$('${{ steps.get_package_versions.outputs.data }}' | (jq '.name'))
          output=""
          for release in $(echo $responses | jq '.[] | .name')
          do
             output+="- $release\n          "
          done
          sed "s/\$IMAGES_OPTIONS/$output/g" $GITHUB_WORKSPACE/.github/workflows/release.template.yml > $GITHUB_WORKSPACE/.github/workflows/release.yml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated package versions
