name: Generate packages release

on:
  workflow_dispatch:
      inputs:
        environment:
          type: environment
          description: Select the environment
jobs:
  get-images-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: octokit/request-action@v2.x
        id: get_package_versions
        with:
          route: GET /user/packages/container/altinn-access-management-frontend/versions
          mediaType: | # The | is significant!
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #id: list_package_versions
      - name: Generates release.yml with package version
        run: |  
         responses='${{ steps.get_package_versions.outputs.data }}'
          output=""
          for release in $(echo $responses | jq '.[] | .name')
          do
             output+="- $release\n          "
          done
          echo $output
          sed 's/\$IMAGES_OPTIONS/$output/g' ${{ github.workspace }}/.github/workflows/release.template.yml > ${{ github.workspace }}/.github/workflows/release.yml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated package versions
