name: Generate packages release

on:
  workflow_dispatch:
      inputs:
        environment:
          type: environment
          description: Select the environment
jobs:
  get-images-list:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_ACCESS_TOKEN }}
        
      - uses: octokit/request-action@v2.x
        id: get_package_versions
        with:
          route: GET /user/packages/container/altinn-access-management-frontend/versions
          mediaType: | # The | is significant!
            format: raw
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #id: list_package_versions
        
      - name: Generates release.yml with package version
        run: |  
         responses='${{ steps.get_package_versions.outputs.data }}'
          output=""
          for release in $(echo $responses | jq '.[] | .metadata.container.tags[0]')
          do
            #if: $($release != null && $release != "")
              output+="- $release\n          "
          done
          echo $output
          sed "s/\$IMAGES_OPTIONS/$output/g" ${{ github.workspace }}/.github/workflows/release.template.yml > ${{ github.workspace }}/.github/workflows/release.yml
      
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "dhanasneham@gmail.com"
          git config user.email "dhanasneham@gmail.com"
          git config -l | grep url
      
      - name: commit release
          # Stage the file, commit and push
        run: |
          git remote set-url origin https://${{ secrets.COMMIT_ACCESS_TOKEN }}@github.com/acn-dgopa/altinn-access-management-frontend.git
          git config -l | grep url
          git add ${{ github.workspace }}/.github/workflows/release.yml
          git commit -m "updated package versions"
          git push
      #- uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
       #   commit_message: Generated images
        #  commit_user_name: acn-dgopa
