name: Playwright Tests
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Environment
jobs:
  e2e-tests:
    
    name: 'Playwright end to end tests'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: [AT21, AT22, AT23, AT24]
        
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: yarn --immutable
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Running yarn tests
      working-directory: playwright
      run: yarn run env:${{ matrix.environment }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/playwright-report
        retention-days: 30
