name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      version:
        type: choice
        description: Select the package version
        options:
          - "755bbb9b73cb1422403745ecd6bfba6a0d365e37"
          - null
          - null
          - "b3dc679ef6b728b9952b27b5b0132e021491325c"
          - null
          - null
          - "ea60f3b6a2769194131ebce2e5f67623c4dfce56"
          - null
          - null
          - "b6ef6ef2a6390f218a95d3047f9fe9411ab62774"
          - null
          - null
          - "833b6dd987042ec3cf86ef74e7be2f2eddf87157"
          - null
          - null
          - "075a75f17a7d0ec6647bae5e0686f94f5d06589e"
          - null
          - null
          - "5949c9491846914e3e5c9731eeae6deeaeec6210"
          - null
          - null
          - "c13c56bacbcd7dc3e98f1b66e788beb0985507f6"
          - null
          - null
          - "1ee92ba907e540674a9df351613a2414b5658cea"
          - null
          - null
          
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: acn-dgopa/altinn-access-management-frontend
  CONTAINER_APP_CONTAINER_NAME: altinnaccessmanagementui
  CONTAINER_APP_NAME: altinnaccessmanagementui-app
  CONTAINER_APP_RESOURCE_GROUP_NAME: am-ui-rg
  
jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy to containerapp
      uses: azure/CLI@v1
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:@{{ inputs.version }}
    - name: logout
      run: >
        az logout
