name: template-deploy-container.yml

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'Environment'
      tag:
        type: string
        required: true
        description: 'Container Tag'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: altinn/altinn-access-management-frontend
  CONTAINER_APP_CONTAINER_NAME: altinnaccessmanagementui

jobs:
  deploy:
    name: Deploy Container
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      name: GitHub CR Login
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
      name: Azure Login
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/CLI@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2
      name: Update Container App
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update \
            --name ${{ vars.CONTAINER_APP_NAME }} \
            --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} \
            --resource-group ${{ vars.CONTAINER_APP_RESOURCE_GROUP_NAME }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}