name: 'Tests: Cypress Schedule'

run-name: End-to-End Tests

on:
  schedule:
    - cron:  '0 5 * * *' # every day at 05:00 UTC

jobs:
  schedule:
    name: 'Cypress'
    strategy:
      fail-fast: false
      matrix:
        environment: [at21, at22, at23, at24, tt02]
    uses: './.github/workflows/template-test-cypress.yml'
    with:
      environment: ${{ matrix.environment }}